# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created: Mon Mar 30 23:51:06 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 319)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 486, 260))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pb4 = QtGui.QPushButton(self.widget)
        self.pb4.setObjectName("pb4")
        self.gridLayout.addWidget(self.pb4, 3, 0, 1, 1)
        self.pb5 = QtGui.QPushButton(self.widget)
        self.pb5.setObjectName("pb5")
        self.gridLayout.addWidget(self.pb5, 3, 1, 1, 1)
        self.pb6 = QtGui.QPushButton(self.widget)
        self.pb6.setObjectName("pb6")
        self.gridLayout.addWidget(self.pb6, 3, 2, 1, 1)
        self.pbMul = QtGui.QPushButton(self.widget)
        self.pbMul.setObjectName("pbMul")
        self.gridLayout.addWidget(self.pbMul, 3, 3, 1, 1)
        self.pb1 = QtGui.QPushButton(self.widget)
        self.pb1.setObjectName("pb1")
        self.gridLayout.addWidget(self.pb1, 4, 0, 1, 1)
        self.pb2 = QtGui.QPushButton(self.widget)
        self.pb2.setObjectName("pb2")
        self.gridLayout.addWidget(self.pb2, 4, 1, 1, 1)
        self.pb3 = QtGui.QPushButton(self.widget)
        self.pb3.setObjectName("pb3")
        self.gridLayout.addWidget(self.pb3, 4, 2, 1, 1)
        self.pbSub = QtGui.QPushButton(self.widget)
        self.pbSub.setObjectName("pbSub")
        self.gridLayout.addWidget(self.pbSub, 4, 3, 1, 1)
        self.pb0 = QtGui.QPushButton(self.widget)
        self.pb0.setObjectName("pb0")
        self.gridLayout.addWidget(self.pb0, 5, 0, 1, 2)
        self.pb7 = QtGui.QPushButton(self.widget)
        self.pb7.setObjectName("pb7")
        self.gridLayout.addWidget(self.pb7, 2, 0, 1, 1)
        self.pb8 = QtGui.QPushButton(self.widget)
        self.pb8.setObjectName("pb8")
        self.gridLayout.addWidget(self.pb8, 2, 1, 1, 1)
        self.pb9 = QtGui.QPushButton(self.widget)
        self.pb9.setObjectName("pb9")
        self.gridLayout.addWidget(self.pb9, 2, 2, 1, 1)
        self.pbDiv = QtGui.QPushButton(self.widget)
        self.pbDiv.setObjectName("pbDiv")
        self.gridLayout.addWidget(self.pbDiv, 2, 3, 1, 1)
        self.pbDecimal = QtGui.QPushButton(self.widget)
        self.pbDecimal.setObjectName("pbDecimal")
        self.gridLayout.addWidget(self.pbDecimal, 5, 2, 1, 1)
        self.pbAdd = QtGui.QPushButton(self.widget)
        self.pbAdd.setObjectName("pbAdd")
        self.gridLayout.addWidget(self.pbAdd, 5, 3, 1, 1)
        self.pbCancel = QtGui.QPushButton(self.widget)
        self.pbCancel.setMinimumSize(QtCore.QSize(0, 64))
        self.pbCancel.setObjectName("pbCancel")
        self.gridLayout.addWidget(self.pbCancel, 2, 4, 2, 1)
        self.pbEqual = QtGui.QPushButton(self.widget)
        self.pbEqual.setMinimumSize(QtCore.QSize(0, 64))
        self.pbEqual.setObjectName("pbEqual")
        self.gridLayout.addWidget(self.pbEqual, 4, 4, 2, 1)
        self.mainDisplay = QtGui.QLineEdit(self.widget)
        self.mainDisplay.setMinimumSize(QtCore.QSize(0, 40))
        self.mainDisplay.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(16)
        self.mainDisplay.setFont(font)
        self.mainDisplay.setMaxLength(12)
        self.mainDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mainDisplay.setReadOnly(True)
        self.mainDisplay.setObjectName("mainDisplay")
        self.gridLayout.addWidget(self.mainDisplay, 0, 0, 1, 5)
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 101, 21))
        self.label.setObjectName("label")
        self.cbThousands = QtGui.QCheckBox(self.frame)
        self.cbThousands.setGeometry(QtCore.QRect(250, 10, 231, 17))
        self.cbThousands.setChecked(True)
        self.cbThousands.setObjectName("cbThousands")
        self.decimalBox = QtGui.QSpinBox(self.frame)
        self.decimalBox.setGeometry(QtCore.QRect(140, 10, 41, 21))
        self.decimalBox.setMaximum(5)
        self.decimalBox.setObjectName("decimalBox")
        self.gridLayout.addWidget(self.frame, 6, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pb7, self.pb8)
        MainWindow.setTabOrder(self.pb8, self.pb9)
        MainWindow.setTabOrder(self.pb9, self.pbDiv)
        MainWindow.setTabOrder(self.pbDiv, self.pbCancel)
        MainWindow.setTabOrder(self.pbCancel, self.pb4)
        MainWindow.setTabOrder(self.pb4, self.pb5)
        MainWindow.setTabOrder(self.pb5, self.pb6)
        MainWindow.setTabOrder(self.pb6, self.pbMul)
        MainWindow.setTabOrder(self.pbMul, self.pb1)
        MainWindow.setTabOrder(self.pb1, self.pb2)
        MainWindow.setTabOrder(self.pb2, self.pb3)
        MainWindow.setTabOrder(self.pb3, self.pbSub)
        MainWindow.setTabOrder(self.pbSub, self.pbEqual)
        MainWindow.setTabOrder(self.pbEqual, self.pb0)
        MainWindow.setTabOrder(self.pb0, self.pbDecimal)
        MainWindow.setTabOrder(self.pbDecimal, self.pbAdd)
        MainWindow.setTabOrder(self.pbAdd, self.decimalBox)
        MainWindow.setTabOrder(self.decimalBox, self.cbThousands)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pb4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.pb5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.pb6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pbMul.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.pb1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pb2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pb3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSub.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pb0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pb7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.pb8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.pb9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDiv.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDecimal.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEqual.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.mainDisplay.setText(QtGui.QApplication.translate("MainWindow", "0.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Decimal Digits", None, QtGui.QApplication.UnicodeUTF8))
        self.cbThousands.setText(QtGui.QApplication.translate("MainWindow", "Display Thousands\' Separator", None, QtGui.QApplication.UnicodeUTF8))

